### ISSUE TITLE
YouTube - This extension no longer works when trying to capture text from a video

### ISSUE THREAD

**Issue by efab2022** [brian-girko/image-reader#12]
This used to work a few days/weeks ago.
Today I tried to extract text from a tutorial and the extension does not show the window where recognition and results are shown.. this still works on other websites, so it seems to be affecting a few websites only (youtube being the most obvious one)

- ❌ youtube - eg: https://www.youtube.com/watch?v=4JFVhJyTZ44
- ❌ pypi.org - eg: https://pypi.org/project/Pillow/

Other pages still work well:
- ✅ most other pages - eg: https://www.geeksforgeeks.org/how-to-use-glob-function-to-find-files-recursively-in-python/
- ✅ https://webextension.org/listing/ocr.html?version=0.3.7&type=install

Not sure if this is caused by youtube's latest attempt to block things, but could also be caused by a recent code change to the extension (seeing there were recent changes and that it affects other non yt sites)

Hope this helps

Thanks for maintaining such an amazing tool that makes our lives easier :)

**Comment by brian-girko** [comment]
This is on Firefox, right? If so, it is fixed on the next release.
